apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: tile2-service
  namespace: default
  annotations:
    networking.internal.knative.dev/serviceType: ClusterLocal
    networking.knative.dev/ingress.class: kourier
spec:
  template:
    metadata:
      annotations:
        networking.knative.dev/port: "8083"
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "5"
        autoscaling.knative.dev/target: "1"
    spec:
      containers:
        - image: soutobias/titiler-xarray:v2
          ports:
            - name: http1
              containerPort: 8083
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8083
            initialDelaySeconds: 5
            periodSeconds: 10
          env:
            - name: REDIS_HOST
              value: "redis-cache"
            - name: REDIS_PORT
              value: "6379"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: false
            seccompProfile:
              type: RuntimeDefault